export enum FEnums {
    AssetManagement = "103",
    Settings = "995",
    MySettings = "95",
    Import = "945",
    Export = "950",
    InventoryManagement = "353",
    InventoryConfiguration = "356",
    AssetConfiguration = "106",
    DeviceManagement = "253",
    DeviceConfiguration = "256",
    NewSession = "12",
    AssetPowerCabling = "153",
    AssetNetworkCabling = "156",
    InventoryImport = "365",
    InventoryExport = "368",
    DevicePowerCabling = "259",
    DeviceNetworkCabling = "262",
    DeviceImport = "265",
    DeviceExport = "268",
    ImportCables = "373",
    ExportCables = "376",
    Discover = "306",
    Monitor = "309",
    IntelDCMConsole = "303",
    Configure = "312",
    // PlatformOS = "353",
    // Applications = "356",
    PhysicalCompute = "403",
    VirtualCompute = "406",
    CloudCompute = "409",
    ComputeAlerts = "412",
    ModelBusinessService = "453",
    BusinessServiceAlerts = "459",

    TrendsAndForecast = "509",
    FilterCapacity = "512",
    OptimizeCapacity = "515",
    ReportBuilder = "653",
    Optimize = "903",
    Stop = "921",
    Start = "924",
    ManageAuditSessions = "603",
    AuditDataCenter = "606",
    InventoryReconciliation = "609",
    BackgroundTasks = "18",
    Reminders = "21",
    UserProfile = "8",
    Documentation = "6",
    DataCenterHierarchy = "905",
    InventoryStoreHierarchy = "910",
    ManageBusinessService = "456",
    Home = "990",
    MigrateDB = "915",
    PowerBI = "506",
    AnalyticsAndCharts = "503",
    close = "4",
    FloorLayout = "258",
    StopNetZoom = "909",
    StartNetZoom = "906",
}

export enum RightMouseMenuTreeNode {
    SortAtoZ = "Sort A-Z",
    SortZtoA = "Sort Z-A",
    Refresh = "Refresh",
    FindInInventory = "Find in Inventory",
    Copy = "Copy",
    Paste = "Paste",
    Cut = "Cut",
    Delete = "Delete",
    Up = "Move Up",
    Down = "Move Down",
    Export = "Export Properties",
    UpdateProperties = 'Update Properties',
    ImportPowerCables = "Import Power Cables",
    ImportNetworkCables = "Import Network Cables",
    ExportNetworkCables = "Export Network Cables",
    ExportPowerCables = "Export Power Cables",
    OrderSubnodes = "Order Subnodes Asc",
    DonotOrderSubnodes = "Do not Order Subnodes",
    SetProperty = "Set Property",
    AddCabling = "Add to Cable",
    EditPowerCabling = "Edit Power Cabling",
    EditNetworkCabling = "Edit Network Cabling",
    ReviewNetworkCabling = "Review Network Cabling",
    ReviewPowerCabling = "Review Power Cabling",
    ImportDevices = "Import Devices",
    ExportDevices = "Export Devices",
    BlockAll = "Block All",
    unblockAll = "Unblock All",
    NormalSlot = "Normal SLOT",
    BlockSlot = "Block SLOT",
    ReserveSlot = "Reserve SLOT",
    NormalRU = "Normal RU",
    BlockRU = "Block RU",
    ReserveRU = "Reserve RU",
    EmptyDevice = "Empty Device",
    EmptyRack = `Empty Rack`,
    SwapDeviceViews = "Swap Device Views",
    NormalPort = "Normal Port",
    BlockPort = "Block Port",
    ReservePort = "Reserve Port",
    BADPort = "BAD Port",
    AddNewAuditSession = "Add New Audit Session",
    Add = "Add",
    Approve = "Approve",
    Reject = "Reject",
    Open = "Open",
    Close = "Close",
    Accept = "Accept",
    ImportAuditInventory = "Import",
    ExportAuditInventory = "Export",
    Snapshot = "Snapshot",
    AddRoom = "Add Room",
    AddFloor = "Add Floor",
    AddNewSiteDataCenter = "Add New Data Center Site",
    AddBin = "Add Bin",
    EmptySiteDataCenter = "Empty Data Center Site",
    DeleteSiteDataCenter = "Delete Data Center Site",
    EmptyFloor = "Empty Floor",
    EmptyBin = "Empty Bin",
    DeleteFloor = "Delete Floor",
    DeleteRoom = "Delete Room",
    EmptyRoom = "Empty Room",
    DeleteBin = "Delete Bin",
    AddNewBusinessService = "Add New Business Service",
    AddDCISegment = "Add DCI Segment",
    DeleteDCISegment = "Delete DCI Segment",
    addDCI = "Add DCI",
    DeleteDCI = "Delete DCI",
    DisconnectCable = "Disconnect Cable",
    DisconnectPort = "Disconnect Port",
    HideAll = "Hide All",
    UnhideAll = "Unhide All",
    PushUp = "Push Up",
    PushDown = "Push Down",
    MapPorts = "Map Ports",
    Info = "Info",
    ImportDevicesToInventory = "Import Devices to Inventory",
    EditFloorLayout = "Edit Floor Layout",
    Charts = "Charts",
    CopyHyperlink = "Copy Hyperlink"
}
export const ChartEntityNameArr = {
    EntityNames: 'Site, Room, Floor, Rack; Device; MountedDevice; Cable;',
}
export enum HomePageSubMenus {
    DataCenterExplorer = 99002,
    Dashboards = 99004,
    GoogleMap = 99009
}

export enum DropableControlElementEnums {
    SiteName = "SiteName",
    RoomName = "RoomName",
    FloorName = "FloorName",
    LocationName = "LocationName",
    DeviceName = "DeviceName"
}

export const NewSessionParameterObject: any = [{
    VariableContext: "Session",
    VariableName: "State",
    SessionValue: "99"
}]

export const FeatureQAEnums = {
    Notes: "Notes",
    Report: "Report",
    Attach: "Attach",
    Property: "Property",
    Device: "Device",
    DataCenter: "DataCenter",
    Alerts: "Alerts",
    Inventory: "Inventory",
    Reconciliation: "Reconciliation",
    Log: "Log",
    Physical: "Physical",
    Cloud: "Cloud"
}

export enum EntityNameEnums {
    ReportProfile = "ReportProfile",
    AlertProfile = "AlertProfile",
    AuditSession = "AuditSession",
    AP = "AP",
    Room = "Room",
    Site = "Site",
    Floor = "Floor",
    Bin = "Bin",
    BS = "BS",
    DCI = "DCI",
    LayoutFilterProfile = 'LayoutFilterProfile',
    ChartProfile = 'ChartProfile'
}

export const CATEGORY = {
    MAIN_GROUP: {
        Authorization_20: "Users and Authorization",
        TeamsAndAuthorization: "Teams and Authorization",
        TenantsAndAuthorization: "Tenants and Authorization",
        Datasets: "Datasets",
        NetZoomAbout: "NetZoomAbout",
        ForensicLog: "Forensic Log",
        DCI: "DCI",
        Template: "Template",
        Integration: "Integration",
        Subscribe: "Subscribe",
        FloorLayout: "Floor Layout",
        DataCenterHierarchy: "Data Center Hierarchy",
        InventoryHierarchy: "Inventory Hierarchy"
    },
    SUB_GROUP: {
        Site_Role_and_License_Authorization_by_User: "User Authorization",
        Feature_Authorization_by_User: "Authorize Features by User",
        Feature_Authorization_by_Team: "Authorize Features by Team",
        Feature_Authorization_by_Tenants: "Authorize Features by Tenant",
        Feature_Authorization_by_Role: "Authorize Features by Role",
        DelegateToAnotherUser: "Delegate to Another User",
        Vitals: "Vitals",
        AuthorizeItemsByRole: "Authorize Entities by Role",
        AuthorizeItemsByUser: "Authorize Entities by User",
        AuthorizeItemsByTenant: "Authorize Entities by Tenant",
        AuthorizeItemsByTeam: "Authorize Entities by Team",
        BI: "BI",
        AllForensicLog: "All Forensic Log",
        DCI: "DCI",
        StatusbarTemplates: "StatusBar Templates",
        AlertTemplate: "Alert Template",
        ReportTemplate: "Report Template",
        ServiceNow: "ServiceNow",
        AlertDelivery: "Alert Delivery",
        ReportDelivery: "Report Delivery",
        FloorLayoutFilter: 'Floor Layout Filter',
        DataCenterHierarchy: "Data Center Hierarchy",
        InventoryHierarchy: "Inventory Hierarchy",
        ChartAndDashboardTemplate: 'Chart and Dashboard Template'

    }
}

export const reuseDataForFeatures: string[] = [
    FEnums.AssetManagement,
    FEnums.AssetConfiguration,
    FEnums.AssetPowerCabling,
    FEnums.AssetNetworkCabling,
    FEnums.DeviceManagement,
    FEnums.DeviceConfiguration,
    FEnums.DevicePowerCabling,
    FEnums.DeviceNetworkCabling,
    FEnums.PhysicalCompute,
    FEnums.FloorLayout
]